
![](https://numpy.org/doc/stable/_static/numpylogo.svg)

NumPy (Numerical Python) là gói cơ bản cho tính toán khoa học bằng Python. Nó là một thư viện Python cung cấp đối tượng mảng đa chiều, các đối tượng dẫn xuất khác nhau (chẳng hạn như mảng bị che và ma trận) và một loạt các quy trình cho các thao tác nhanh trên mảng, bao gồm thao tác toán học, logic, hình dạng, sắp xếp, chọn, I/O , biến đổi Fourier rời rạc, đại số tuyến tính cơ bản, phép toán thống kê cơ bản, mô phỏng ngẫu nhiên, v.v.

Người dùng NumPy bao gồm tất cả mọi người từ lập trình viên mới bắt đầu đến các nhà nghiên cứu có kinh nghiệm thực hiện nghiên cứu và phát triển khoa học và công nghiệp hiện đại.

API NumPy được sử dụng rộng rãi trong Pandas, SciPy, Matplotlib, scikit-learning, scikit-image và hầu hết các dữ liệu khác và các gói Python khoa học.

Thư viện NumPy chứa các cấu trúc dữ liệu ma trận và mảng đa chiều. Nó cung cấp ndarray, một đối tượng mảng n chiều đồng nhất, với các phương thức để hoạt động hiệu quả.

# Cài đặt

Nếu bạn đã có Python, bạn có thể cài đặt NumPy bằng:


```
conda install numpy
```
hoặc
```
pip install numpy
```





# Mục mới

[văn bản liên kết](https://)# ndarray numpy vs list python
![](https://camo.githubusercontent.com/f2feeac81e3c55f8daf75887a2c6041642496106ada557416cbb95d25cb9d599/68747470733a2f2f646f63732e676f6f676c652e636f6d2f64726177696e67732f642f652f32504143582d3176546b44744b594d5556647066566233545470725f387272567470616c32644f6b6e5555454f753835774a315269747a484866356e734a717a314f30536e5474384277674a6a78584d5958794971732f7075623f773d37323626683d333936)

Trong Python, mọi thứ đều là đối tượng, có nghĩa là ngay cả những int đơn giản cũng là đối tượng, với tất cả các máy móc cần thiết để làm cho đối tượng hoạt động. Chúng tôi gọi chúng là "Số nguyên đóng hộp". Ngược lại, NumPy sử dụng các kiểu số nguyên thủy (float, ints) giúp lưu trữ và tính toán hiệu quả.

Mảng NumPy nhanh hơn và nhỏ gọn hơn danh sách Python. Một mảng tiêu thụ ít bộ nhớ hơn và thuận tiện khi sử dụng. NumPy sử dụng ít bộ nhớ hơn nhiều để lưu trữ dữ liệu và nó cung cấp cơ chế chỉ định các loại dữ liệu. Điều này cho phép mã được tối ưu hóa hơn nữa.

NumPy cung cấp cho bạn rất nhiều cách nhanh chóng và hiệu quả để tạo mảng và thao tác dữ liệu số bên trong chúng. Mặc dù danh sách Python có thể chứa các loại dữ liệu khác nhau trong một danh sách, nhưng tất cả các phần tử trong mảng NumPy phải đồng nhất. Các phép toán được thực hiện trên các mảng sẽ cực kỳ kém hiệu quả nếu các mảng không đồng nhất.

In [ ]:
import sys
import numpy as np

a = np.array([1, 2, 3, 4])
b = [1, 2, 3, 4]
c = [1, '2', 3, 4]
print(a,b,c)

[1 2 3 4] [1, 2, 3, 4] [1, '2', 3, 4]


In [ ]:
from sys import getsizeof

print(a.nbytes)
print(getsizeof(b))

32
120


# Data structure in Numpy

Mảng là cấu trúc dữ liệu trọng tâm của Numpy. Mảng bao gồm một lưới các giá trị và nó chứa thông tin về dữ liệu thô, cách xác định vị trí phần tử và cách diễn giải phần tử. Nó có một mạng lưới các phần tử có thể được lập chỉ mục theo nhiều cách khác nhau. Các phần tử đều có cùng kiểu, được gọi là dtype mảng.

Một mảng có thể được lập chỉ mục bởi một bộ các số nguyên không âm, bởi các phép toán luận, bởi một mảng khác hoặc bởi các số nguyên. Thứ hạng của mảng là số chiều. Hình dạng của mảng là một bộ số nguyên cho biết kích thước của mảng dọc theo mỗi chiều.

In [ ]:
a = np.array([1, 2], dtype='i')
print(a)
print(a.dtype)

a = np.array([1, 2], dtype='i4') # 32-bit signed integer
print(a)
print(a.dtype)

a = np.array([1, 2], dtype='f8') # 64-bit floating-point number
print(a)
print(a.dtype)

a = np.array([1, 2], dtype='f') # 32-bit floating-point number
print(a)
print(a.dtype)

a = np.array([1, 2], dtype='c16') # 128-bit complex floating-point number
print(a)
print(a.dtype)

[1 2]
int32
[1 2]
int32
[1. 2.]
float64
[1. 2.]
float32
[1.+0.j 2.+0.j]
complex128


# Numpy array

NumPy được sử dụng để làm việc với mảng. Đối tượng mảng trong NumPy được gọi là ndarray.

Chúng ta có thể tạo một đối tượng NumPy ndarray bằng cách sử dụng hàm array().

Để truy cập các phần tử mảng ta sử dụng các chỉ mục. Lập chỉ mục mảng cũng giống như truy cập một phần tử mảng. Bạn có thể truy cập một phần tử mảng bằng cách tham khảo số chỉ mục của nó.

Các chỉ mục trong mảng NumPy bắt đầu bằng 0, nghĩa là phần tử đầu tiên có chỉ mục 0 và phần tử thứ hai có chỉ mục 1, v.v.

Lưu ý: Sử dụng lập chỉ mục phủ định để truy cập một mảng từ cuối.

In [ ]:
a = np.array([1, 2, 3, 4, 5, 6])

b = np.array([[1, 2, 3, 4], [5, 6, 7, 8], [9, 10, 11, 12]])

print(a)
print(a.shape)
print(b)
print(b.shape)

[1 2 3 4 5 6]
(6,)
[[ 1  2  3  4]
 [ 5  6  7  8]
 [ 9 10 11 12]]
(3, 4)


In [ ]:
print(a[0], a[1])
print(a[1:3])
print(a[0:])
print(a[::2])

print(b[1,2])

c = np.array([[[1, 2, 3], [4, 5, 6]], [[7, 8, 9], [10, 11, 12]]])
print(c)
print(c[0, 1, 2])

1 2
[2 3]
[1 2 3 4 5 6]
[1 3 5]
7
[[[ 1  2  3]
  [ 4  5  6]]

 [[ 7  8  9]
  [10 11 12]]]
6


#Copy vs View

Sự khác biệt chính giữa bản sao (copy) và dạng xem (view) của một mảng là bản sao là một mảng mới và dạng xem chỉ là dạng xem của mảng ban đầu.

Bản sao sở hữu dữ liệu và mọi thay đổi đối với bản sao sẽ không ảnh hưởng đến mảng ban đầu và mọi thay đổi đối với mảng ban đầu sẽ không ảnh hưởng đến bản sao.

Chế độ xem không sở hữu dữ liệu và mọi thay đổi được thực hiện đối với chế độ xem sẽ ảnh hưởng đến mảng ban đầu và mọi thay đổi được thực hiện đối với mảng ban đầu sẽ ảnh hưởng đến chế độ xem.

In [ ]:
arr = np.array([1, 2, 3, 4, 5])
x = arr.copy()
arr[0] = 42

print(arr)
print(x)

[42  2  3  4  5]
[1 2 3 4 5]


In [ ]:
arr = np.array([1, 2, 3, 4, 5])
x = arr.view()
arr[0] = 42

print(arr)
print(x)

[42  2  3  4  5]
[42  2  3  4  5]


Nối mảng NumPy
Nối có nghĩa là đặt nội dung của hai hoặc nhiều mảng trong một mảng.

Trong SQL, chúng tôi nối các bảng dựa trên một khóa, trong khi ở NumPy, chúng tôi nối các mảng theo trục.

Chúng ta chuyển một chuỗi các mảng mà chúng ta muốn nối vào hàm concatenate(), cùng với trục. Nếu trục không được thông qua một cách rõ ràng, nó được lấy bằng 0.

In [ ]:
arr1 = np.array([1, 2, 3])

arr2 = np.array([4, 5, 6])

arr = np.concatenate((arr1, arr2))

print(arr)

[1 2 3 4 5 6]


In [ ]:
arr1 = np.array([[1, 2], [3, 4]])

arr2 = np.array([[5, 6], [7, 8]])

arr_1 = np.concatenate((arr1, arr2), axis=1)
arr_0 = np.concatenate((arr1, arr2), axis=0)

print(arr_1)
print(arr_0)

[[1 2 5 6]
 [3 4 7 8]]
[[1 2]
 [3 4]
 [5 6]
 [7 8]]


Xếp chồng (Stack) giống như ghép nối, điểm khác biệt duy nhất là xếp chồng được thực hiện dọc theo một trục mới.

Chúng ta có thể nối hai mảng 1-D dọc theo trục thứ hai, điều này sẽ dẫn đến việc đặt chúng chồng lên nhau, tức là. xếp chồng.

Chúng tôi chuyển một chuỗi các mảng mà chúng tôi muốn nối với phương thức stack() cùng với trục.

In [ ]:
arr1 = np.array([1, 2, 3])

arr2 = np.array([4, 5, 6])

arr = np.stack((arr1, arr2), axis=1)

print(arr)

[[1 4]
 [2 5]
 [3 6]]


# Tính toán số liệu




In [ ]:
a = np.array([1, 2, 3, 4])

In [ ]:
# Tính tổng
a.sum()

10

In [ ]:
# Trung bình cộng
a.mean()

2.5

In [ ]:
# Độ lệch chuẩn
a.std()

1.118033988749895

In [ ]:
# Phương sai
a.var()

1.25

In [ ]:
A = np.array([
    [1, 2, 3],
    [4, 5, 6],
    [7, 8, 9]
])

print(A.sum())
print(A.sum(axis = 1))
print(A.sum(axis = 0))

45
[ 6 15 24]
[12 15 18]


# [Linear Algebra](https://numpy.org/doc/stable/reference/routines.linalg.html)

Các hàm đại số tuyến tính NumPy dựa trên BLAS và LAPACK để cung cấp các triển khai cấp thấp hiệu quả của các thuật toán đại số tuyến tính tiêu chuẩn. Các thư viện đó có thể được cung cấp bởi chính NumPy bằng cách sử dụng các phiên bản C của một tập hợp con các triển khai tham chiếu của chúng, nhưng khi có thể, các thư viện được tối ưu hóa cao tận dụng chức năng của bộ xử lý chuyên dụng sẽ được ưu tiên hơn.
[Numpy linear]

In [ ]:
A = np.array([
    [1, 2, 3],
    [4, 5, 6],
    [7, 8, 9]
])

B = np.array([
    [6, 5],
    [4, 3],
    [2, 1]
])



In [ ]:
A.dot(B)

array([[20, 14],
       [56, 41],
       [92, 68]])

In [ ]:
A @ B

array([[20, 14],
       [56, 41],
       [92, 68]])

In [ ]:
B.T

array([[6, 4, 2],
       [5, 3, 1]])

# Các hàm Numpy hữu ích

In [ ]:
np.random.random(size=2)

array([0.87708947, 0.32446474])

In [ ]:
np.random.normal(size=2)

array([0.93981565, 0.52947201])

In [ ]:
np.random.rand(2, 4)

array([[0.34236125, 0.09414517, 0.34374024, 0.04237371],
       [0.69555007, 0.94025066, 0.14954168, 0.69661373]])

In [ ]:
np.arange(10)

array([0, 1, 2, 3, 4, 5, 6, 7, 8, 9])

In [ ]:
np.arange(5, 10)

array([5, 6, 7, 8, 9])

Định hình lại mảng (Reshape)
Định hình lại có nghĩa là thay đổi hình dạng của một mảng.

Hình dạng của một mảng là số phần tử trong mỗi chiều.

Bằng cách định hình lại, chúng ta có thể thêm hoặc xóa kích thước hoặc thay đổi số lượng phần tử trong mỗi kích thước.

In [ ]:
np.arange(10).reshape(2, 5)

array([[0, 1, 2, 3, 4],
       [5, 6, 7, 8, 9]])

In [ ]:
np.arange(10).reshape(5, 2)

array([[0, 1],
       [2, 3],
       [4, 5],
       [6, 7],
       [8, 9]])

np.linspace()

Trả về các số cách đều nhau trong một khoảng thời gian xác định.

Trả về số mẫu cách đều nhau, được tính trong khoảng thời gian [bắt đầu, dừng].

In [ ]:
np.linspace(0, 1, 5)

array([0.  , 0.25, 0.5 , 0.75, 1.  ])

In [ ]:
np.linspace(0, 1, 20)

array([0.        , 0.05263158, 0.10526316, 0.15789474, 0.21052632,
       0.26315789, 0.31578947, 0.36842105, 0.42105263, 0.47368421,
       0.52631579, 0.57894737, 0.63157895, 0.68421053, 0.73684211,
       0.78947368, 0.84210526, 0.89473684, 0.94736842, 1.        ])

In [ ]:
np.zeros(5)

array([0., 0., 0., 0., 0.])

In [ ]:
np.ones(5)

array([1., 1., 1., 1., 1.])

In [ ]:
np.empty(5)

array([1., 1., 1., 1., 1.])

In [ ]:
np.identity(3)

array([[1., 0., 0.],
       [0., 1., 0.],
       [0., 0., 1.]])

In [ ]:
np.eye(3, 3)

array([[1., 0., 0.],
       [0., 1., 0.],
       [0., 0., 1.]])